#!/bin/bash
set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
SRC="$ROOT/src"
OUT="$ROOT/theme.css"

echo "/* NC Theme — auto-generated by build.sh */" > "$OUT"
echo "" >> "$OUT"

# Order: variables → base components → overrides → CRT (toggleable)
for file in \
  "$SRC/classic/variables.css" \
  "$SRC"/base/*.css \
  "$SRC/classic/overrides.css" \
  "$SRC/crt/effects.css"
do
  if [ -f "$file" ]; then
    echo "/* === $(basename "$file") === */" >> "$OUT"
    cat "$file" >> "$OUT"
    echo "" >> "$OUT"
  else
    echo "WARNING: $file not found" >&2
  fi
done

echo "Built $OUT"
