#!/bin/bash
set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
SRC="$ROOT/src"

build_theme() {
  local name="$1"
  shift
  local out="$ROOT/$name/theme.css"

  echo "/* $name — auto-generated by build.sh */" > "$out"
  echo "" >> "$out"

  for file in "$@"; do
    if [ -f "$SRC/$file" ]; then
      echo "/* === $(basename "$file") === */" >> "$out"
      cat "$SRC/$file" >> "$out"
      echo "" >> "$out"
    else
      echo "WARNING: $SRC/$file not found" >&2
    fi
  done

  echo "Built $out"
}

# Collect base files in order
BASE_FILES=()
for f in "$SRC"/base/*.css; do
  [ -f "$f" ] && BASE_FILES+=("base/$(basename "$f")")
done

# Classic = classic/variables + base/* + classic/overrides
build_theme "nc-theme-classic" \
  "classic/variables.css" \
  "${BASE_FILES[@]}" \
  "classic/overrides.css"

# CRT = classic/variables + base/* + classic/overrides + crt/effects
build_theme "nc-theme-crt" \
  "classic/variables.css" \
  "${BASE_FILES[@]}" \
  "classic/overrides.css" \
  "crt/effects.css"

echo "Done!"
